### PR TITLE
Fix #4 Fatal error: undefined is not a function

### LINKED ISSUE #4: Fatal error: undefined is not a function
With node v0.12.7 (latest available with brew), I get a fatal error:

```
Running "appdmg:target" (appdmg) task
Fatal error: undefined is not a function
TypeError: undefined is not a function
    at EventEmitter.<anonymous> (/Users/felicienfrancois/git/TweakStyle/node_modules/grunt-appdmg/tasks/appdmg.js:39:41)
    at EventEmitter.emit (events.js:107:17)
    at Pipeline._progress (/Users/felicienfrancois/git/TweakStyle/node_modules/grunt-appdmg/node_modules/appdmg/lib/pipeline.js:20:11)
    at Pipeline._runStep (/Users/felicienfrancois/git/TweakStyle/node_modules/grunt-appdmg/node_modules/appdmg/lib/pipeline.js:45:8)
    at Pipeline._run (/Users/felicienfrancois/git/TweakStyle/node_modules/grunt-appdmg/node_modules/appdmg/lib/pipeline.js:97:8)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

This is due to the use of String.repeat in tasks/appdmg.js:39 which is not defined in nodejs 0.12.7

### PR DESCRIPTION
**Pull request by felicienfrancois**
Use grunt.util.repeat instead of String.repeat

### CODE REVIEW

**Comment by htanjo** [comment]
Thanks for the PR!
I fixed the args of `grunt.util.repeat` (4afe30587648fe62b38bd2b0049654b01fa5014c) and merged it.

**Comment by felicienfrancois** [comment]
Oops, you're right on the arguments order.
Strange as I tested it and it was working. Maybe `grunt.util.repeat` is accepting both order ?

**Comment by htanjo** [comment]
I'm not so sure about the behavior but I got collapsed log from your original code on my environment.

```
[ 1/20] Looking for target... 1[ OK ]
[ 2/20] Reading JSON Specification... 1[SKIP]
...
```

Anyway, now everything looks good! Thanks for your help!

**Comment by felicienfrancois** [comment]
OK, your right. It was not breaking but was not good at all.

**Pull request merged**
